### ISSUE TITLE
`libsass` bindings not found

### ISSUE THREAD

**Issue by lyhcode** [trunk-studio/agricloud-mobile-cart#6]
```
[10:37:57] Error: `libsass` bindings not found in /Users/lyhcode/trunk-studio/agricloud-mobile-cart/node_modules/gulp-sass/node_modules/node-sass/vendor/darwin-x64-14/binding.node. Try reinstalling `node-sass`?
    at Object.sass.getBinaryPath (/Users/lyhcode/trunk-studio/agricloud-mobile-cart/node_modules/gulp-sass/node_modules/node-sass/lib/extensions.js:148:11)
    at Object.<anonymous> (/Users/lyhcode/trunk-studio/agricloud-mobile-cart/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:16:36)
    at Module._compile (module.js:460:26)
    at Module._extensions..js (module.js:478:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/lyhcode/trunk-studio/agricloud-mobile-cart/node_modules/babel-core/lib/api/register/node.js:214:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/lyhcode/trunk-studio/agricloud-mobile-cart/node_modules/gulp-sass/index.js:163:21)
```

**Comment by lyhcode** [comment]
try =>

```
npm rebuild node-sass
```
